name: Docker Image CI
on:
  push:
    branches: [release, main]
  workflow_dispatch:
jobs:
  build:
    name: "Build & Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Version
        run: |
          CI_VERSION=$(cat ./src/VERSION)
          echo "CI_VERSION=$CI_VERSION" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t shrihariprakash/nitrogen:$CI_VERSION -t "shrihariprakash/nitrogen:latest"
      - name: Docker Hub Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Hub Push
        run: docker push shrihariprakash/nitrogen --all-tags
  acceptance_tests:
    name: "Run Acceptance Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACCEPTANCE_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
           owner: 'gopalcs1988',
           repo: 'nitrogen-acceptance-tests',
           workflow_id: 'playwright.yml',
           ref: 'main'
          })
